### ISSUE TITLE
Deployment/update scripts

### ISSUE THREAD

**Issue by DOBEN** [Concordium/concordium-umbrella-oracle#2]
**Task description**

Add deployment/update scripts

**Sub-tasks**
- [ ] Deploying umbrella feeds contract, registry, and staking bank (setting up the protocol).
- [ ] Registering contracts in registry
- [ ] Updating the staking bank contract.
- [ ] Updating the umbrella feeds contract.
